name: on-pull-request

on:
  pull_request:

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    env:
      # renovate: datasource=docker depName=rhysd/actionlint
      ACTIONLINT_VERSION: 1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: actionlint
        run: |
          docker run --rm \
            --volume "${PWD}:/repo" \
            --workdir /repo \
            "rhysd/actionlint:${ACTIONLINT_VERSION}" -color
